#loader contenttweaker
import mods.contenttweaker.Material;
import mods.contenttweaker.MaterialSystem;
import mods.contenttweaker.PartBuilder;
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;
import mods.contenttweaker.Color;

# MATERIALS FILE
# ============================================

# -custom-blocks
genBlock("mica", <blockMaterial:rock>, 5, 6, "pickaxe", 1);

# -custom-items
genItem("infi_single");

# -custom-liquids
genFluid("cotc_juice", "00ff00", 6000, false, 15, 1000, 6000, false, "contenttweaker:fluids/liquid", "contenttweaker:fluids/liquid_flowing", <blockmaterial:water>);

# -custom-moltens
genFluid("cotc_glowing", "ffff00", 6000, false, 5, 1000, 6000, false, "contenttweaker:fluids/molten", "contenttweaker:fluids/molten_flowing", <blockmaterial:lava>);

# -custom-gases
genFluid("cotc_sky", "0000ff", 6000, true, 5, 1000, 6000, false, "contenttweaker:fluids/gas", "contenttweaker:fluids/gas_flowing", <blockmaterial:water>);

# -custom-plasmas
genFluid("cotc_tesla", "ff00ff", 6000, true, 5, 1000, 6000, false, "contenttweaker:fluids/plasma", "contenttweaker:fluids/plasma_flowing", <blockmaterial:lava>);

# -custom-parts
var boule = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("boule").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("boule").build();
var chain = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("chain").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("chain").build();
var chunk = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("chunk").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("chunk").build();
var coil = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("coil").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("coil").build();
var concentrated_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("concentrated_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("concentratedOre").build();
var curved_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("curved_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("curvedPlate").build();
var dense_fibers = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("dense_fibers").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("denseFibers").build();
var dense_wire = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("dense_wire").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("denseWire").build();
var drill_head = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("drill_head").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("drillHead").build();
var exquisite_gem = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("exquisite_gem").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("exquisiteGem").build();
var fiber = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("fiber").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("fiber").build();
var fibers = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("fibers").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("fibers").build();
var fine_dust = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("fine_dust").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("fineDust").build();
var fine_wire = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("fine_wire").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("fineWire").build();
var foil = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("foil").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("foil").build();
var gearbox = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("gearbox").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("gearbox").build();
var gem = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("gem").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("gem").build();
var hot_ingot = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("hot_ingot").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("hotIngot").build();
var infused_wafer = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("infused_wafer").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("infusedWafer").build();
var infused_boule = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("infused_boule").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("infusedBoule").build();
var large_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("large_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("largePlate").build();
var large_scrap = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("large_scrap").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("largeScrap").build();
var lens = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("lens").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("lens").build();
var long_stick = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("long_stick").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("longStick").build();
var morsel = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("morsel").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("morsel").build();
var pebble = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("pebble").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("pebble").build();
var piece = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("piece").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("piece").build();
var powder = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("powder").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("powder").build();
var pure_dust = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("pure_dust").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("pureDust").build();
var rail = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("rail").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("rail").build();
var raw_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("raw_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("rawOre").build();
var rotor = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("rotor").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("rotor").build();
var saw_blade = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("saw_blade").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("sawBlade").build();
var scrap = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("scrap").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("scrap").build();
var screw = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("screw").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("screw").build();
var screwed_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("screwed_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("screwedPlate").build();
var small_bolt = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_bolt").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallBolt").build();
var small_casing = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_casing").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallCasing").build();
var small_centrifuged_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_centrifuged_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallCentrifugedOre").build();
var small_crushed_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_crushed_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("smallCrushedOre").build();
var small_fine_dust = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_fine_dust").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallFineDust").build();
var small_gear = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_gear").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallGear").build();
var small_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallPlate").build();
var small_powder = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_powder").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallPowder").build();
var small_purified_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_purified_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallPurifiedOre").build();
var small_rod = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_rod").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallRod").build();
var small_screwed_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_screwed_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallScrewedPlate").build();
var small_spring = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_spring").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallSpring").build();
var solid_metal = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("solid_metal").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("solidMetal").build();
var spring = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("spring").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("spring").build();
var stick = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("stick").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("stick").build();
var stone_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("stone_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("stonePlate").build();
var superior_gem = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("superior_gem").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("superiorGem").build();
var tiny_fine_dust = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("tiny_fine_dust").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("tinyFineDust").build();
var tiny_powder = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("tiny_powder").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("tinyPowder").build();
var tough_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("tough_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("toughPlate").build();
var turbine_blade = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("turbine_blade").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("turbineBlade").build();
var wafer = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("wafer").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("wafer").build();
var wire = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("wire").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("wire").build();
var wood_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("wood_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("woodPlate").build();

# -partgroups
var dust_parts = ["dust", "small_dust", "tiny_dust"] as string[];
var fine_parts = ["fine_dust", "small_fine_dust", "tiny_fine_dust"] as string[];
var powder_parts = ["powder", "small_powder", "tiny_powder"] as string[];
var ore_parts = ["rock", "ore_rock", "cluster", "clump", "shard", "crushed_ore", "small_crushed_ore", "purified_ore", "small_purified_ore", "centrifuged_ore", "small_centrifuged_ore", "pure_dust", "raw_ore", "chunk", "scrap", "large_scrap"] as string[];
var gem_parts = ["gem", "chipped_gem", "flawed_gem", "crystal", "flawless_gem", "exquisite_gem", "superior_gem", "piece", "lens"] as string[];
var smelt_parts = ["ingot", "morsel", "nugget", "casing", "plate", "curved_plate", "tough_plate", "dense_plate", "small_rod", "rod", "long_rod", "small_spring", "large_spring", "beam", "bolt", "screw", "round", "foil", "ring", "small_gear", "gear", "small_plate", "spring", "chain", "rail", "large_plate", "small_bolt", "small_casing", "small_screwed_plate"] as string[];
var plastic_parts = ["ingot", "morsel", "nugget", "casing", "plate", "curved_plate", "tough_plate", "dense_plate", "small_rod", "rod", "long_rod", "beam", "bolt", "screw", "round", "foil", "ring", "small_plate", "spring", "chain", "large_plate", "small_casing", "small_screwed_plate"] as string[];
var rubber_parts = ["ingot", "morsel", "nugget", "casing", "plate", "curved_plate", "tough_plate", "dense_plate", "round", "ring", "small_plate", "large_plate", "small_casing"] as string[];
var conductive_parts = ["wire", "fine_wire", "dense_wire", "coil"] as string[];
var blast_parts = ["hot_ingot"] as string[];
var machine_parts = ["turbine_blade", "drill_head", "saw_blade", "rotor", "gearbox"] as string[];
var string_parts = ["fiber", "fibers", "dense_fibers"] as string[];
var semi_conductive_parts = ["boule", "infused_boule", "wafer", "infused_wafer"] as string[];
var wood_parts = ["wood_plate", "stick", "long_stick"] as string[];
var stone_parts = ["pebble"] as string[];

# -materials
var oak = MaterialSystem.getMaterialBuilder().setName("Oak").setColor(Color.fromHex("966f35")).build();
var spruce = MaterialSystem.getMaterialBuilder().setName("Spruce").setColor(Color.fromHex("734712")).build();
var birch = MaterialSystem.getMaterialBuilder().setName("Birch").setColor(Color.fromHex("e0d1a4")).build();
var jungle = MaterialSystem.getMaterialBuilder().setName("Jungle").setColor(Color.fromHex("d19e71")).build();
var acacia = MaterialSystem.getMaterialBuilder().setName("Acacia").setColor(Color.fromHex("d1732c")).build();
var dark_oak = MaterialSystem.getMaterialBuilder().setName("Dark Oak").setColor(Color.fromHex("472104")).build();
var granite = MaterialSystem.getMaterialBuilder().setName("Granite").setColor(Color.fromHex("d19d80")).build();
var diabase = MaterialSystem.getMaterialBuilder().setName("Diabase").setColor(Color.fromHex("262321")).build();
var rhyolite = MaterialSystem.getMaterialBuilder().setName("Rhyolite").setColor(Color.fromHex("7b877b")).build();
var kimberlite = MaterialSystem.getMaterialBuilder().setName("Kimberlite").setColor(Color.fromHex("414d4c")).build();
var komatiite = MaterialSystem.getMaterialBuilder().setName("Komatiite").setColor(Color.fromHex("dbb856")).build();
var dacite = MaterialSystem.getMaterialBuilder().setName("Dacite").setColor(Color.fromHex("d5dbdb")).build();
var gneiss = MaterialSystem.getMaterialBuilder().setName("Gneiss").setColor(Color.fromHex("595c63")).build();
var eclogite = MaterialSystem.getMaterialBuilder().setName("Eclogite").setColor(Color.fromHex("918273")).build();
var marble = MaterialSystem.getMaterialBuilder().setName("Marble").setColor(Color.fromHex("e3e8e7")).build();
var quartzite = MaterialSystem.getMaterialBuilder().setName("Quartzite").setColor(Color.fromHex("91857d")).build();
var hornfels = MaterialSystem.getMaterialBuilder().setName("Hornfels").setColor(Color.fromHex("36918e")).build();
var schist = MaterialSystem.getMaterialBuilder().setName("Schist").setColor(Color.fromHex("3d805f")).build();
var soapstone = MaterialSystem.getMaterialBuilder().setName("Soapstone").setColor(Color.fromHex("c0c9d1")).build();
var migmatite = MaterialSystem.getMaterialBuilder().setName("Migmatite").setColor(Color.fromHex("6e7985")).build();
var chalk = MaterialSystem.getMaterialBuilder().setName("Chalk").setColor(Color.fromHex("ded0ca")).build();
var dolomite = MaterialSystem.getMaterialBuilder().setName("Dolomite").setColor(Color.fromHex("65705e")).build();
var gabbro = MaterialSystem.getMaterialBuilder().setName("Gabbro").setColor(Color.fromHex("7e7985")).build();
var conglomerate = MaterialSystem.getMaterialBuilder().setName("Conglomerate").setColor(Color.fromHex("0a0a12")).build();
var greywacke = MaterialSystem.getMaterialBuilder().setName("Greywacke").setColor(Color.fromHex("bcc2be")).build();
var limestone = MaterialSystem.getMaterialBuilder().setName("Limestone").setColor(Color.fromHex("bccca3")).build();
var shale = MaterialSystem.getMaterialBuilder().setName("Shale").setColor(Color.fromHex("abadb8")).build();
var siltstone = MaterialSystem.getMaterialBuilder().setName("Siltstone").setColor(Color.fromHex("ab8572")).build();
var coal = MaterialSystem.getMaterialBuilder().setName("Coal").setColor(Color.fromHex("0d0c12")).build();
var lignite = MaterialSystem.getMaterialBuilder().setName("Lignite").setColor(Color.fromHex("292626")).build();
var charcoal = MaterialSystem.getMaterialBuilder().setName("Charcoal").setColor(Color.fromHex("1c1616")).build();
var wool = MaterialSystem.getMaterialBuilder().setName("Wool").setColor(Color.fromHex("f2f4f7")).build();
var bauxite = MaterialSystem.getMaterialBuilder().setName("Bauxite").setColor(Color.fromHex("ff9b79")).build();
var galena = MaterialSystem.getMaterialBuilder().setName("Galena").setColor(Color.fromHex("af78b6")).build();
var polyethylene = MaterialSystem.getMaterialBuilder().setName("Polyethylene").setColor(Color.fromHex("a8a59d")).build();
var rubber = MaterialSystem.getMaterialBuilder().setName("Rubber").setColor(Color.fromHex("4a473f")).build();
var lithium = MaterialSystem.getMaterialBuilder().setName("Lithium").setColor(Color.fromHex("b4bc84")).build();
var beryllium = MaterialSystem.getMaterialBuilder().setName("Beryllium").setColor(Color.fromHex("0f2d0f")).build();
var boron = MaterialSystem.getMaterialBuilder().setName("Boron").setColor(Color.fromHex("363d31")).build();
var carbon = MaterialSystem.getMaterialBuilder().setName("Carbon").setColor(Color.fromHex("404040")).build();
var sodium = MaterialSystem.getMaterialBuilder().setName("Sodium").setColor(Color.fromHex("000c91")).build();
var magnesium = MaterialSystem.getMaterialBuilder().setName("Magnesium").setColor(Color.fromHex("d99fe3")).build();
var aluminium = MaterialSystem.getMaterialBuilder().setName("Aluminium").setColor(Color.fromHex("6fe1ed")).build();
var silicon = MaterialSystem.getMaterialBuilder().setName("Silicon").setColor(Color.fromHex("060033")).build();
var phosphorus = MaterialSystem.getMaterialBuilder().setName("Phosphorus").setColor(Color.fromHex("7a4907")).build();
var sulfur = MaterialSystem.getMaterialBuilder().setName("Sulfur").setColor(Color.fromHex("a38b12")).build();
var potassium = MaterialSystem.getMaterialBuilder().setName("Potassium").setColor(Color.fromHex("ccc6a5")).build();
var calcium = MaterialSystem.getMaterialBuilder().setName("Calcium").setColor(Color.fromHex("fff2b3")).build();
var scandium = MaterialSystem.getMaterialBuilder().setName("Scandium").setColor(Color.fromHex("689c97")).build();
var titanium = MaterialSystem.getMaterialBuilder().setName("Titanium").setColor(Color.fromHex("e398db")).build();
var vanadium = MaterialSystem.getMaterialBuilder().setName("Vanadium").setColor(Color.fromHex("252833")).build();
var chrome = MaterialSystem.getMaterialBuilder().setName("Chrome").setColor(Color.fromHex("fde0ff")).build();
var manganese = MaterialSystem.getMaterialBuilder().setName("Manganese").setColor(Color.fromHex("e0c5df")).build();
var iron = MaterialSystem.getMaterialBuilder().setName("Iron").setColor(Color.fromHex("d9d7d9")).build();
var cobalt = MaterialSystem.getMaterialBuilder().setName("Cobalt").setColor(Color.fromHex("3152e8")).build();
var nickel = MaterialSystem.getMaterialBuilder().setName("Nickel").setColor(Color.fromHex("e6d6aa")).build();
var copper = MaterialSystem.getMaterialBuilder().setName("Copper").setColor(Color.fromHex("f5b753")).build();
var zinc = MaterialSystem.getMaterialBuilder().setName("Zinc").setColor(Color.fromHex("dae5e8")).build();
var gallium = MaterialSystem.getMaterialBuilder().setName("Gallium").setColor(Color.fromHex("75c7aa")).build();
var germanium = MaterialSystem.getMaterialBuilder().setName("Germanium").setColor(Color.fromHex("eaf4f9")).build();
var arsenic = MaterialSystem.getMaterialBuilder().setName("Arsenic").setColor(Color.fromHex("cfd4c3")).build();
var selenium = MaterialSystem.getMaterialBuilder().setName("Selenium").setColor(Color.fromHex("630e0e")).build();
var rubidium = MaterialSystem.getMaterialBuilder().setName("Rubidium").setColor(Color.fromHex("855151")).build();
var strontium = MaterialSystem.getMaterialBuilder().setName("Strontium").setColor(Color.fromHex("b0a884")).build();
var yttrium = MaterialSystem.getMaterialBuilder().setName("Yttrium").setColor(Color.fromHex("b1c9ab")).build();
var zirconium = MaterialSystem.getMaterialBuilder().setName("Zirconium").setColor(Color.fromHex("b5b833")).build();
var niobium = MaterialSystem.getMaterialBuilder().setName("Niobium").setColor(Color.fromHex("5c246b")).build();
var molybdenum = MaterialSystem.getMaterialBuilder().setName("Molybdenum").setColor(Color.fromHex("ba9bd4")).build();
var technetium = MaterialSystem.getMaterialBuilder().setName("Technetium").setColor(Color.fromHex("b1efda")).build();
var ruthenium = MaterialSystem.getMaterialBuilder().setName("Ruthenium").setColor(Color.fromHex("eae3e7")).build();
var rhodium = MaterialSystem.getMaterialBuilder().setName("Rhodium").setColor(Color.fromHex("efeaeb")).build();
var palladium = MaterialSystem.getMaterialBuilder().setName("Palladium").setColor(Color.fromHex("6e26ff")).build();
var silver = MaterialSystem.getMaterialBuilder().setName("Silver").setColor(Color.fromHex("e1f5f2")).build();
var cadmium = MaterialSystem.getMaterialBuilder().setName("Cadmium").setColor(Color.fromHex("406e99")).build();
var indium = MaterialSystem.getMaterialBuilder().setName("Indium").setColor(Color.fromHex("8b00b5")).build();
var tin = MaterialSystem.getMaterialBuilder().setName("Tin").setColor(Color.fromHex("2d73ff")).build();
var antimony = MaterialSystem.getMaterialBuilder().setName("Antimony").setColor(Color.fromHex("ebdcab")).build();
var tellurium = MaterialSystem.getMaterialBuilder().setName("Tellurium").setColor(Color.fromHex("52919e")).build();
var iodine = MaterialSystem.getMaterialBuilder().setName("Iodine").setColor(Color.fromHex("5f3368")).build();
var caesium = MaterialSystem.getMaterialBuilder().setName("Caesium").setColor(Color.fromHex("a4a0ad")).build();
var barium = MaterialSystem.getMaterialBuilder().setName("Barium").setColor(Color.fromHex("a84d14")).build();
var lanthanum = MaterialSystem.getMaterialBuilder().setName("Lanthanum").setColor(Color.fromHex("96a2ab")).build();
var cerium = MaterialSystem.getMaterialBuilder().setName("Cerium").setColor(Color.fromHex("516675")).build();
var praseodymium = MaterialSystem.getMaterialBuilder().setName("Praseodymium").setColor(Color.fromHex("163d59")).build();
var neodymium = MaterialSystem.getMaterialBuilder().setName("Neodymium").setColor(Color.fromHex("727287")).build();
var promethium = MaterialSystem.getMaterialBuilder().setName("Promethium").setColor(Color.fromHex("ab7291")).build();
var samarium = MaterialSystem.getMaterialBuilder().setName("Samarium").setColor(Color.fromHex("486959")).build();
var europium = MaterialSystem.getMaterialBuilder().setName("Europium").setColor(Color.fromHex("9c7e75")).build();
var gadolinium = MaterialSystem.getMaterialBuilder().setName("Gadolinium").setColor(Color.fromHex("bab88c")).build();
var terbium = MaterialSystem.getMaterialBuilder().setName("Terbium").setColor(Color.fromHex("788a5a")).build();
var dysprosium = MaterialSystem.getMaterialBuilder().setName("Dysprosium").setColor(Color.fromHex("6e3054")).build();
var holmium = MaterialSystem.getMaterialBuilder().setName("Holmium").setColor(Color.fromHex("877e6d")).build();
var erbium = MaterialSystem.getMaterialBuilder().setName("Erbium").setColor(Color.fromHex("6d877f")).build();
var thulium = MaterialSystem.getMaterialBuilder().setName("Thulium").setColor(Color.fromHex("072742")).build();
var ytterbium = MaterialSystem.getMaterialBuilder().setName("Ytterbium").setColor(Color.fromHex("3f3f4a")).build();
var lutetium = MaterialSystem.getMaterialBuilder().setName("Lutetium").setColor(Color.fromHex("7b989c")).build();
var hafnium = MaterialSystem.getMaterialBuilder().setName("Hafnium").setColor(Color.fromHex("afbbce")).build();
var tantalum = MaterialSystem.getMaterialBuilder().setName("Tantalum").setColor(Color.fromHex("bccccf")).build();
var tungsten = MaterialSystem.getMaterialBuilder().setName("Tungsten").setColor(Color.fromHex("101024")).build();
var rhenium = MaterialSystem.getMaterialBuilder().setName("Rhenium").setColor(Color.fromHex("dfd2ef")).build();
var osmium = MaterialSystem.getMaterialBuilder().setName("Osmium").setColor(Color.fromHex("0000ff")).build();
var iridium = MaterialSystem.getMaterialBuilder().setName("Iridium").setColor(Color.fromHex("edfffd")).build();
var platinum = MaterialSystem.getMaterialBuilder().setName("Platinum").setColor(Color.fromHex("ced7db")).build();
var gold = MaterialSystem.getMaterialBuilder().setName("Gold").setColor(Color.fromHex("ffd95c")).build();
var mercury = MaterialSystem.getMaterialBuilder().setName("Mercury").setColor(Color.fromHex("ff5c5c")).build();
var thallium = MaterialSystem.getMaterialBuilder().setName("Thallium").setColor(Color.fromHex("c6d7f2")).build();
var lead = MaterialSystem.getMaterialBuilder().setName("Lead").setColor(Color.fromHex("9771ab")).build();
var bismuth = MaterialSystem.getMaterialBuilder().setName("Bismuth").setColor(Color.fromHex("54946e")).build();
var polonium = MaterialSystem.getMaterialBuilder().setName("Polonium").setColor(Color.fromHex("66421f")).build();
var astatine = MaterialSystem.getMaterialBuilder().setName("Astatine").setColor(Color.fromHex("2a2b30")).build();
var francium = MaterialSystem.getMaterialBuilder().setName("Francium").setColor(Color.fromHex("434a46")).build();
var radium = MaterialSystem.getMaterialBuilder().setName("Radium").setColor(Color.fromHex("c7c6b5")).build();
var actinium = MaterialSystem.getMaterialBuilder().setName("Actinium").setColor(Color.fromHex("415fc1")).build();
var thorium = MaterialSystem.getMaterialBuilder().setName("Thorium").setColor(Color.fromHex("2a1c36")).build();
var protactinium = MaterialSystem.getMaterialBuilder().setName("Protactinium").setColor(Color.fromHex("dadff2")).build();
var uranium = MaterialSystem.getMaterialBuilder().setName("Uranium").setColor(Color.fromHex("00ff4c")).build();
var neptunium = MaterialSystem.getMaterialBuilder().setName("Neptunium").setColor(Color.fromHex("4b4de3")).build();
var plutonium = MaterialSystem.getMaterialBuilder().setName("Plutonium").setColor(Color.fromHex("abacd4")).build();
var americium = MaterialSystem.getMaterialBuilder().setName("Americium").setColor(Color.fromHex("ffa382")).build();
var curium = MaterialSystem.getMaterialBuilder().setName("Curium").setColor(Color.fromHex("3b4066")).build();
var berkelium = MaterialSystem.getMaterialBuilder().setName("Berkelium").setColor(Color.fromHex("825f19")).build();
var californium = MaterialSystem.getMaterialBuilder().setName("Californium").setColor(Color.fromHex("c44310")).build();
var einsteinium = MaterialSystem.getMaterialBuilder().setName("Einsteinium").setColor(Color.fromHex("0e2784")).build();
var fermium = MaterialSystem.getMaterialBuilder().setName("Fermium").setColor(Color.fromHex("abaf79")).build();
var mendelevium = MaterialSystem.getMaterialBuilder().setName("Mendelevium").setColor(Color.fromHex("79afa9")).build();
var nobelium = MaterialSystem.getMaterialBuilder().setName("Nobelium").setColor(Color.fromHex("a679af")).build();
var lawrencium = MaterialSystem.getMaterialBuilder().setName("Lawrencium").setColor(Color.fromHex("c1b343")).build();
var rutherfordium = MaterialSystem.getMaterialBuilder().setName("Rutherfordium").setColor(Color.fromHex("d4bfa7")).build();
var dubnium = MaterialSystem.getMaterialBuilder().setName("Dubnium").setColor(Color.fromHex("b5c9c7")).build();
var seaborgium = MaterialSystem.getMaterialBuilder().setName("Seaborgium").setColor(Color.fromHex("9dc3c7")).build();
var bohrium = MaterialSystem.getMaterialBuilder().setName("Bohrium").setColor(Color.fromHex("5c3f3f")).build();
var hassium = MaterialSystem.getMaterialBuilder().setName("Hassium").setColor(Color.fromHex("8f7951")).build();
var meitnerium = MaterialSystem.getMaterialBuilder().setName("Meitnerium").setColor(Color.fromHex("b097ab")).build();
var darmstadtium = MaterialSystem.getMaterialBuilder().setName("Darmstadtium").setColor(Color.fromHex("cee6b1")).build();
var roentgenium = MaterialSystem.getMaterialBuilder().setName("Roentgenium").setColor(Color.fromHex("5f6b63")).build();
var copernicium = MaterialSystem.getMaterialBuilder().setName("Copernicium").setColor(Color.fromHex("7c8c8f")).build();
var nihonium = MaterialSystem.getMaterialBuilder().setName("Nihonium").setColor(Color.fromHex("a8bab2")).build();
var flerovium = MaterialSystem.getMaterialBuilder().setName("Flerovium").setColor(Color.fromHex("bac3cc")).build();
var moscovium = MaterialSystem.getMaterialBuilder().setName("Moscovium").setColor(Color.fromHex("c28274")).build();
var livermorium = MaterialSystem.getMaterialBuilder().setName("Livermorium").setColor(Color.fromHex("ada87b")).build();
var tennessine = MaterialSystem.getMaterialBuilder().setName("Tennessine").setColor(Color.fromHex("a27ee0")).build();
var oganesson = MaterialSystem.getMaterialBuilder().setName("Oganesson").setColor(Color.fromHex("949494")).build();
var kanthal = MaterialSystem.getMaterialBuilder().setName("Kanthal").setColor(Color.fromHex("abad4b")).build();
var nichrome = MaterialSystem.getMaterialBuilder().setName("Nichrome").setColor(Color.fromHex("be7dff")).build();
var tinalloy = MaterialSystem.getMaterialBuilder().setName("Tin Alloy").setColor(Color.fromHex("aacccc")).build();
var magnalium = MaterialSystem.getMaterialBuilder().setName("Magnalium").setColor(Color.fromHex("496281")).build();
var rosegold = MaterialSystem.getMaterialBuilder().setName("Rose Gold").setColor(Color.fromHex("ee6846")).build();
var sterlingsilver = MaterialSystem.getMaterialBuilder().setName("Sterling Silver").setColor(Color.fromHex("cee3e2")).build();
var niobiumtitanium = MaterialSystem.getMaterialBuilder().setName("Niobium Titanium").setColor(Color.fromHex("d37272")).build();
var bluesteel = MaterialSystem.getMaterialBuilder().setName("Blue Steel").setColor(Color.fromHex("0362af")).build();
var redsteel = MaterialSystem.getMaterialBuilder().setName("Red Steel").setColor(Color.fromHex("b51717")).build();
var stainlesssteel = MaterialSystem.getMaterialBuilder().setName("Stainless Steel").setColor(Color.fromHex("9b99b5")).build();
var cobaltbrass = MaterialSystem.getMaterialBuilder().setName("Cobalt Brass").setColor(Color.fromHex("244d8f")).build();
var bismuthbronze = MaterialSystem.getMaterialBuilder().setName("Bismuth Bronze").setColor(Color.fromHex("366035")).build();
var blackbronze = MaterialSystem.getMaterialBuilder().setName("Black Bronze").setColor(Color.fromHex("6d5a1f")).build();
var blacksteel = MaterialSystem.getMaterialBuilder().setName("Black Steel").setColor(Color.fromHex("2f3948")).build();
var pewter = MaterialSystem.getMaterialBuilder().setName("Pewter").setColor(Color.fromHex("bbd1ab")).build();
var galvanized_steel = MaterialSystem.getMaterialBuilder().setName("Galvanized Steel").setColor(Color.fromHex("777f5e")).build();
var tungstensteel = MaterialSystem.getMaterialBuilder().setName("Tungstensteel").setColor(Color.fromHex("1b2431")).build();
var iridium_alloy = MaterialSystem.getMaterialBuilder().setName("Iridium Alloy").setColor(Color.fromHex("eaefee")).build();
var advanced_alloy = MaterialSystem.getMaterialBuilder().setName("Advanced Alloy").setColor(Color.fromHex("e84629")).build();
var bronze = MaterialSystem.getMaterialBuilder().setName("Bronze").setColor(Color.fromHex("ff881a")).build();
var electrum = MaterialSystem.getMaterialBuilder().setName("Electrum").setColor(Color.fromHex("f9e600")).build();
var constantan = MaterialSystem.getMaterialBuilder().setName("Constantan").setColor(Color.fromHex("fd5c17")).build();
var steel = MaterialSystem.getMaterialBuilder().setName("Steel").setColor(Color.fromHex("869a9b")).build();
var brass = MaterialSystem.getMaterialBuilder().setName("Brass").setColor(Color.fromHex("f2b600")).build();
var invar = MaterialSystem.getMaterialBuilder().setName("Invar").setColor(Color.fromHex("b0ae6a")).build();
var hssg = MaterialSystem.getMaterialBuilder().setName("HSS G").setColor(Color.fromHex("929434")).build();
var hsse = MaterialSystem.getMaterialBuilder().setName("HSS E").setColor(Color.fromHex("335c2a")).build();
var hsss = MaterialSystem.getMaterialBuilder().setName("HSS S").setColor(Color.fromHex("63283e")).build();
var dilithium = MaterialSystem.getMaterialBuilder().setName("Dilithium").setColor(Color.fromHex("e4e2ba")).build();
var titanium_aluminide = MaterialSystem.getMaterialBuilder().setName("Titanium Aluminide").setColor(Color.fromHex("033d47")).build();
var titanium_iridium = MaterialSystem.getMaterialBuilder().setName("Titanium Iridium").setColor(Color.fromHex("e9b4b5")).build();
var redstone_alloy = MaterialSystem.getMaterialBuilder().setName("Redstone Alloy").setColor(Color.fromHex("ea2a15")).build();
var electrical_steel = MaterialSystem.getMaterialBuilder().setName("Electrical Steel").setColor(Color.fromHex("a9acb2")).build();
var conductive_iron = MaterialSystem.getMaterialBuilder().setName("Conductive Iron").setColor(Color.fromHex("b79d9a")).build();
var dark_steel = MaterialSystem.getMaterialBuilder().setName("Dark Steel").setColor(Color.fromHex("2e332f")).build();
var construction_alloy = MaterialSystem.getMaterialBuilder().setName("Construction Alloy").setColor(Color.fromHex("b5b18d")).build();
var alumite = MaterialSystem.getMaterialBuilder().setName("Alumite").setColor(Color.fromHex("ffc9f0")).build();
var osmiridium = MaterialSystem.getMaterialBuilder().setName("Osmiridium").setColor(Color.fromHex("7999c8")).build();
var redalloy = MaterialSystem.getMaterialBuilder().setName("Red Alloy").setColor(Color.fromHex("ff0000")).build();
var electrum_flux = MaterialSystem.getMaterialBuilder().setName("Gelid Enderium").setColor(Color.fromHex("f4b024")).build();
var signalum = MaterialSystem.getMaterialBuilder().setName("Signalum").setColor(Color.fromHex("fe3a01")).build();
var lumium = MaterialSystem.getMaterialBuilder().setName("Lumium").setColor(Color.fromHex("ffffb6")).build();
var enderium = MaterialSystem.getMaterialBuilder().setName("Enderium").setColor(Color.fromHex("008839")).build();
var aluminum_brass = MaterialSystem.getMaterialBuilder().setName("Aluminum Brass").setColor(Color.fromHex("f2d048")).build();
var knightslime = MaterialSystem.getMaterialBuilder().setName("Knightslime").setColor(Color.fromHex("c741d8")).build();
var pig_iron = MaterialSystem.getMaterialBuilder().setName("Pig Iron").setColor(Color.fromHex("e2a69e")).build();
var cupronickel = MaterialSystem.getMaterialBuilder().setName("Cupronickel").setColor(Color.fromHex("d89115")).build();
var aluminum_bronze = MaterialSystem.getMaterialBuilder().setName("Aluminum Bronze").setColor(Color.fromHex("f2a348")).build();
var nickel_aluminum_bronze = MaterialSystem.getMaterialBuilder().setName("NickelAluminum Bronze").setColor(Color.fromHex("ead48c")).build();
var yttrium_barium_cuprate = MaterialSystem.getMaterialBuilder().setName("Yttrium Barium Cuprate").setColor(Color.fromHex("3b0c08")).build();
var purple_steel = MaterialSystem.getMaterialBuilder().setName("Purple Steel").setColor(Color.fromHex("71006d")).build();
var voidensteel = MaterialSystem.getMaterialBuilder().setName("Voidensteel").setColor(Color.fromHex("531135")).build();
var white_gold = MaterialSystem.getMaterialBuilder().setName("White Gold").setColor(Color.fromHex("fffcc4")).build();
var nichromium = MaterialSystem.getMaterialBuilder().setName("Nichromium").setColor(Color.fromHex("945252")).build();
var chromodium = MaterialSystem.getMaterialBuilder().setName("Chromodium").setColor(Color.fromHex("7b0425")).build();
var fluxalitium = MaterialSystem.getMaterialBuilder().setName("Fluxalitium").setColor(Color.fromHex("ffe097")).build();
var spectraclium = MaterialSystem.getMaterialBuilder().setName("Spectraclium").setColor(Color.fromHex("e8fffe")).build();
var obsidian = MaterialSystem.getMaterialBuilder().setName("Obsidian").setColor(Color.fromHex("420042")).build();
var nether_star = MaterialSystem.getMaterialBuilder().setName("Nether Star").setColor(Color.fromHex("fafeff")).build();
var green_sapphire = MaterialSystem.getMaterialBuilder().setName("Green Sapphire").setColor(Color.fromHex("47b560")).build();
var diamond = MaterialSystem.getMaterialBuilder().setName("Diamond").setColor(Color.fromHex("c9ffff")).build();
var emerald = MaterialSystem.getMaterialBuilder().setName("Emerald").setColor(Color.fromHex("5ebf3b")).build();
var cinnabar = MaterialSystem.getMaterialBuilder().setName("Cinnabar").setColor(Color.fromHex("751d23")).build();
var apatite = MaterialSystem.getMaterialBuilder().setName("Apatite").setColor(Color.fromHex("4887b8")).build();
var monazite = MaterialSystem.getMaterialBuilder().setName("Monazite").setColor(Color.fromHex("557864")).build();
var nether_quartz = MaterialSystem.getMaterialBuilder().setName("Nether Quartz").setColor(Color.fromHex("fffcfa")).build();
var sunny_quartz = MaterialSystem.getMaterialBuilder().setName("Sunny Quartz").setColor(Color.fromHex("fffce8")).build();
var rose_quartz = MaterialSystem.getMaterialBuilder().setName("Rose Quartz").setColor(Color.fromHex("ffe8e8")).build();
var elven_quartz = MaterialSystem.getMaterialBuilder().setName("Elven Quartz").setColor(Color.fromHex("e3ffe7")).build();
var mana_quartz = MaterialSystem.getMaterialBuilder().setName("Mana Quartz").setColor(Color.fromHex("e3f4ff")).build();
var lavender_quartz = MaterialSystem.getMaterialBuilder().setName("Lavender Quartz").setColor(Color.fromHex("e5dff0")).build();
var blaze_quartz = MaterialSystem.getMaterialBuilder().setName("Blaze Quartz").setColor(Color.fromHex("fff1de")).build();
var certus_quartz = MaterialSystem.getMaterialBuilder().setName("Certus Quartz").setColor(Color.fromHex("f0f3ff")).build();
var black_quartz = MaterialSystem.getMaterialBuilder().setName("Black Quartz").setColor(Color.fromHex("242435")).build();
var lava_crystal = MaterialSystem.getMaterialBuilder().setName("Lava Crystal").setColor(Color.fromHex("c6751c")).build();
var electrical = MaterialSystem.getMaterialBuilder().setName("Electrical").setColor(Color.fromHex("aab5b4")).build();
var adamantine = MaterialSystem.getMaterialBuilder().setName("Adamantine").setColor(Color.fromHex("5e3c30")).build();
var cold_iron = MaterialSystem.getMaterialBuilder().setName("Cold Iron").setColor(Color.fromHex("b6d7ef")).build();
var star_steel = MaterialSystem.getMaterialBuilder().setName("Star Steel").setColor(Color.fromHex("070519")).build();
var aquarium = MaterialSystem.getMaterialBuilder().setName("Aquarium").setColor(Color.fromHex("244775")).build();
var ruby = MaterialSystem.getMaterialBuilder().setName("Ruby").setColor(Color.fromHex("b00000")).build();
var amber = MaterialSystem.getMaterialBuilder().setName("Amber").setColor(Color.fromHex("feac63")).build();
var topaz = MaterialSystem.getMaterialBuilder().setName("Topaz").setColor(Color.fromHex("ea7500")).build();
var peridot = MaterialSystem.getMaterialBuilder().setName("Peridot").setColor(Color.fromHex("71e100")).build();
var malachite = MaterialSystem.getMaterialBuilder().setName("Malachite").setColor(Color.fromHex("00f0a8")).build();
var sapphire = MaterialSystem.getMaterialBuilder().setName("Sapphire").setColor(Color.fromHex("4500d5")).build();
var amethyst = MaterialSystem.getMaterialBuilder().setName("Amethyst").setColor(Color.fromHex("da82ff")).build();
var tanzanite = MaterialSystem.getMaterialBuilder().setName("Tanzanite").setColor(Color.fromHex("490f79")).build();
var moonstone = MaterialSystem.getMaterialBuilder().setName("Moonstone").setColor(Color.fromHex("424566")).build();
var red_garnet = MaterialSystem.getMaterialBuilder().setName("Red Garnet").setColor(Color.fromHex("db3c3c")).build();
var yellow_garnet = MaterialSystem.getMaterialBuilder().setName("Yellow Garnet").setColor(Color.fromHex("d6de36")).build();
var aquamarine = MaterialSystem.getMaterialBuilder().setName("Aquamarine").setColor(Color.fromHex("229ce2")).build();

# -solids
lumium.registerParts(dust_parts);
lumium.registerParts(fine_parts);
lumium.registerParts(powder_parts);
granite.registerParts(dust_parts);
granite.registerParts(fine_parts);
granite.registerParts(powder_parts);
diabase.registerParts(dust_parts);
diabase.registerParts(fine_parts);
diabase.registerParts(powder_parts);
rhyolite.registerParts(dust_parts);
rhyolite.registerParts(fine_parts);
rhyolite.registerParts(powder_parts);
kimberlite.registerParts(dust_parts);
kimberlite.registerParts(fine_parts);
kimberlite.registerParts(powder_parts);
komatiite.registerParts(dust_parts);
komatiite.registerParts(fine_parts);
komatiite.registerParts(powder_parts);
dacite.registerParts(dust_parts);
dacite.registerParts(fine_parts);
dacite.registerParts(powder_parts);
gneiss.registerParts(dust_parts);
gneiss.registerParts(fine_parts);
gneiss.registerParts(powder_parts);
eclogite.registerParts(dust_parts);
eclogite.registerParts(fine_parts);
eclogite.registerParts(powder_parts);
marble.registerParts(dust_parts);
marble.registerParts(fine_parts);
marble.registerParts(powder_parts);
quartzite.registerParts(dust_parts);
quartzite.registerParts(fine_parts);
quartzite.registerParts(powder_parts);
hornfels.registerParts(dust_parts);
hornfels.registerParts(fine_parts);
hornfels.registerParts(powder_parts);
schist.registerParts(dust_parts);
schist.registerParts(fine_parts);
schist.registerParts(powder_parts);
soapstone.registerParts(dust_parts);
soapstone.registerParts(fine_parts);
soapstone.registerParts(powder_parts);
migmatite.registerParts(dust_parts);
migmatite.registerParts(fine_parts);
migmatite.registerParts(powder_parts);
chalk.registerParts(dust_parts);
chalk.registerParts(fine_parts);
chalk.registerParts(powder_parts);
dolomite.registerParts(dust_parts);
dolomite.registerParts(fine_parts);
dolomite.registerParts(powder_parts);
gabbro.registerParts(dust_parts);
gabbro.registerParts(fine_parts);
gabbro.registerParts(powder_parts);
conglomerate.registerParts(dust_parts);
conglomerate.registerParts(fine_parts);
conglomerate.registerParts(powder_parts);
greywacke.registerParts(dust_parts);
greywacke.registerParts(fine_parts);
greywacke.registerParts(powder_parts);
limestone.registerParts(dust_parts);
limestone.registerParts(fine_parts);
limestone.registerParts(powder_parts);
shale.registerParts(dust_parts);
shale.registerParts(fine_parts);
shale.registerParts(powder_parts);
siltstone.registerParts(dust_parts);
siltstone.registerParts(fine_parts);
siltstone.registerParts(powder_parts);
ruby.registerParts(dust_parts);
oak.registerParts(dust_parts);
birch.registerParts(dust_parts);
spruce.registerParts(dust_parts);
jungle.registerParts(dust_parts);
acacia.registerParts(dust_parts);
dark_oak.registerParts(dust_parts);
iron.registerParts(dust_parts);
polyethylene.registerParts(dust_parts);
rubber.registerParts(dust_parts);

# -liquids
genFluid("cotm_iron_molten", "d9d7d9", 6000, false, 1, 1000, 6000, false, "contenttweaker:fluids/molten", "contenttweaker:fluids/molten_flowing", <blockmaterial:lava>);
genFluid("cotm_lumium_molten", "ffffb6", 6000, false, 1, 1000, 6000, false, "contenttweaker:fluids/molten", "contenttweaker:fluids/molten_flowing", <blockmaterial:lava>);
genFluid("cotm_polyethylene_molten", "a8a59d", 6000, false, 1, 1000, 5000, false, "contenttweaker:fluids/molten", "contenttweaker:fluids/molten_flowing", <blockmaterial:lava>);
genFluid("cotm_rubber_molten", "4a473f", 6000, false, 1, 1000, 4000, false, "contenttweaker:fluids/molten", "contenttweaker:fluids/molten_flowing", <blockmaterial:lava>);

# -woods
oak.registerParts(wood_parts);
birch.registerParts(wood_parts);
spruce.registerParts(wood_parts);
jungle.registerParts(wood_parts);
acacia.registerParts(wood_parts);
dark_oak.registerParts(wood_parts);

# -stones
granite.registerParts(stone_parts);
diabase.registerParts(stone_parts);
rhyolite.registerParts(stone_parts);
kimberlite.registerParts(stone_parts);
komatiite.registerParts(stone_parts);
dacite.registerParts(stone_parts);
gabbro.registerParts(stone_parts);
gneiss.registerParts(stone_parts);
eclogite.registerParts(stone_parts);
marble.registerParts(stone_parts);
quartzite.registerParts(stone_parts);
hornfels.registerParts(stone_parts);
schist.registerParts(stone_parts);
soapstone.registerParts(stone_parts);
migmatite.registerParts(stone_parts);
chalk.registerParts(stone_parts);
dolomite.registerParts(stone_parts);
conglomerate.registerParts(stone_parts);
greywacke.registerParts(stone_parts);
limestone.registerParts(stone_parts);
shale.registerParts(stone_parts);
siltstone.registerParts(stone_parts);

# -metals
iron.registerParts(smelt_parts);
iron.registerParts(machine_parts);
iron.registerParts(blast_parts);
iron.registerParts(conductive_parts);

# -alloys
lumium.registerParts(smelt_parts);
lumium.registerParts(machine_parts);
lumium.registerParts(blast_parts);
lumium.registerParts(conductive_parts);

# -plastics
polyethylene.registerParts(plastic_parts);

# -rubbers
rubber.registerParts(rubber_parts);

# -gems
ruby.registerParts(gem_parts);

# -ores
lumium.registerParts(ore_parts);
var lumiumStoneOre = lumium.registerPart("ore").getData();
lumiumStoneOre.addDataValue("variants","minecraft:stone");
lumiumStoneOre.addDataValue("hardness","4");
lumiumStoneOre.addDataValue("resistance","6");
lumiumStoneOre.addDataValue("harvestLevel","2");
lumiumStoneOre.addDataValue("harvestTool","pickaxe");
var lumiumStonePoor = lumium.registerPart("poor_ore").getData();
lumiumStonePoor.addDataValue("variants","minecraft:stone");
lumiumStonePoor.addDataValue("hardness","3");
lumiumStonePoor.addDataValue("resistance","6");
lumiumStonePoor.addDataValue("harvestLevel","2");
lumiumStonePoor.addDataValue("harvestTool","pickaxe");
var lumiumStoneDense = lumium.registerPart("dense_ore").getData();
lumiumStoneDense.addDataValue("variants","minecraft:stone");
lumiumStoneDense.addDataValue("hardness","5");
lumiumStoneDense.addDataValue("resistance","6");
lumiumStoneDense.addDataValue("harvestLevel","2");
lumiumStoneDense.addDataValue("harvestTool","pickaxe");

var nether_lumium = MaterialSystem.getMaterialBuilder().setName("Nether Lumium").setColor(Color.fromHex("ffffb6")).build();
nether_lumium.registerParts(ore_parts);
var nether_lumiumNetherOre = nether_lumium.registerPart("ore").getData();
nether_lumiumNetherOre.addDataValue("variants","minecraft:netherrack");
nether_lumiumNetherOre.addDataValue("hardness","4");
nether_lumiumNetherOre.addDataValue("resistance","6");
nether_lumiumNetherOre.addDataValue("harvestLevel","2");
nether_lumiumNetherOre.addDataValue("harvestTool","pickaxe");
var nether_lumiumNetherPoor = nether_lumium.registerPart("poor_ore").getData();
nether_lumiumNetherPoor.addDataValue("variants","minecraft:netherrack");
nether_lumiumNetherPoor.addDataValue("hardness","3");
nether_lumiumNetherPoor.addDataValue("resistance","6");
nether_lumiumNetherPoor.addDataValue("harvestLevel","2");
nether_lumiumNetherPoor.addDataValue("harvestTool","pickaxe");
var nether_lumiumNetherDense = nether_lumium.registerPart("dense_ore").getData();
nether_lumiumNetherDense.addDataValue("variants","minecraft:netherrack");
nether_lumiumNetherDense.addDataValue("hardness","5");
nether_lumiumNetherDense.addDataValue("resistance","6");
nether_lumiumNetherDense.addDataValue("harvestLevel","2");
nether_lumiumNetherDense.addDataValue("harvestTool","pickaxe");

var end_lumium = MaterialSystem.getMaterialBuilder().setName("End Lumium").setColor(Color.fromHex("ffffb6")).build();
end_lumium.registerParts(ore_parts);
var end_lumiumEndOre = end_lumium.registerPart("ore").getData();
end_lumiumEndOre.addDataValue("variants","minecraft:end_stone");
end_lumiumEndOre.addDataValue("hardness","4");
end_lumiumEndOre.addDataValue("resistance","9");
end_lumiumEndOre.addDataValue("harvestLevel","2");
end_lumiumEndOre.addDataValue("harvestTool","pickaxe");
var end_lumiumEndPoor = end_lumium.registerPart("poor_ore").getData();
end_lumiumEndPoor.addDataValue("variants","minecraft:end_stone");
end_lumiumEndPoor.addDataValue("hardness","3");
end_lumiumEndPoor.addDataValue("resistance","9");
end_lumiumEndPoor.addDataValue("harvestLevel","2");
end_lumiumEndPoor.addDataValue("harvestTool","pickaxe");
var end_lumiumEndDense = end_lumium.registerPart("dense_ore").getData();
end_lumiumEndDense.addDataValue("variants","minecraft:end_stone");
end_lumiumEndDense.addDataValue("hardness","5");
end_lumiumEndDense.addDataValue("resistance","9");
end_lumiumEndDense.addDataValue("harvestLevel","2");
end_lumiumEndDense.addDataValue("harvestTool","pickaxe");

var bedrock_lumium = MaterialSystem.getMaterialBuilder().setName("Bedrock Lumium").setColor(Color.fromHex("ffffb6")).build();
var bedrock_lumiumBedrockDense = bedrock_lumium.registerPart("dense_ore").getData();
bedrock_lumiumBedrockDense.addDataValue("variants","minecraft:bedrock");
bedrock_lumiumBedrockDense.addDataValue("hardness","-1");
bedrock_lumiumBedrockDense.addDataValue("resistance","3600000");
bedrock_lumiumBedrockDense.addDataValue("harvestLevel","-1");
bedrock_lumiumBedrockDense.addDataValue("harvestTool","none");



