#loader contenttweaker
import mods.contenttweaker.Material;
import mods.contenttweaker.MaterialSystem;
import mods.contenttweaker.PartBuilder;
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;
import mods.contenttweaker.Color;

# -blocks
genBlock("mica", <blockMaterial:rock>, 5, 6, "pickaxe", 1);

# -parts
var boule = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("boule").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("boule").build();
var chain = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("chain").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("chain").build();
var chunk = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("chunk").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("chunk").build();
var coil = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("coil").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("coil").build();
var concentrated_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("concentrated_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("concentratedOre").build();
var curved_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("curved_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("curvedPlate").build();
var dense_fibers = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("dense_fibers").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("denseFibers").build();
var dense_wire = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("dense_wire").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("denseWire").build();
var drill_head = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("drill_head").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("drillHead").build();
var exquisite_gem = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("exquisite_gem").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("exquisiteGem").build();
var fiber = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("fiber").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("fiber").build();
var fibers = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("fibers").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("fibers").build();
var fine_dust = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("fine_dust").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("fineDust").build();
var fine_wire = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("fine_wire").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("fineWire").build();
var foil = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("foil").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("foil").build();
var gearbox = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("gearbox").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("gearbox").build();
var gem = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("gem").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("gem").build();
var hot_ingot = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("hot_ingot").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("hotIngot").build();
var infused_wafer = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("infused_wafer").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("infusedWafer").build();
var infused_boule = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("infused_boule").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("infusedBoule").build();
var large_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("large_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("largePlate").build();
var large_scrap = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("large_scrap").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("largeScrap").build();
var lens = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("lens").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("lens").build();
var long_stick = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("long_stick").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("longStick").build();
var morsel = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("morsel").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("morsel").build();
var pebble = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("pebble").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("pebble").build();
var piece = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("piece").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("piece").build();
var powder = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("powder").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("powder").build();
var pure_dust = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("pure_dust").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("pureDust").build();
var rail = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("rail").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("rail").build();
var raw_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("raw_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("rawOre").build();
var rotor = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("rotor").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("rotor").build();
var saw_blade = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("saw_blade").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("sawBlade").build();
var scrap = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("scrap").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("scrap").build();
var screw = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("screw").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("screw").build();
var screwed_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("screwed_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("screwedPlate").build();
var small_bolt = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_bolt").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallBolt").build();
var small_casing = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_casing").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallCasing").build();
var small_centrifuged_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_centrifuged_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallCentrifugedOre").build();
var small_crushed_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_crushed_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("smallCrushedOre").build();
var small_fine_dust = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_fine_dust").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallFineDust").build();
var small_gear = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_gear").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallGear").build();
var small_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallPlate").build();
var small_powder = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_powder").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallPowder").build();
var small_purified_ore = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_purified_ore").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallPurifiedOre").build();
var small_rod = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_rod").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallRod").build();
var small_screwed_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_screwed_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallScrewedPlate").build();
var small_spring = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("small_spring").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("smallSpring").build();
var solid_metal = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("solid_metal").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("solidMetal").build();
var spring = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("spring").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("spring").build();
var stick = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("stick").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("stick").build();
var stone_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("stone_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("stonePlate").build();
var superior_gem = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("superior_gem").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("superiorGem").build();
var tiny_fine_dust = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("tiny_fine_dust").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("tinyFineDust").build();
var tiny_powder = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("tiny_powder").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("tinyPowder").build();
var tough_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("tough_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("toughPlate").build();
var turbine_blade = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("turbine_blade").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("turbineBlade").build();
var wafer = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("wafer").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("wafer").build();
var wire = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("wire").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(true).setOreDictName("wire").build();
var wood_plate = mods.contenttweaker.MaterialSystem.getPartBuilder().setName("wood_plate").setPartType(mods.contenttweaker.MaterialSystem.getPartType("item")).setHasOverlay(false).setOreDictName("woodPlate").build();

# -partgroups
var dust_parts = ["dust", "small_dust", "tiny_dust"] as string[];
var fine_parts = ["fine_dust", "small_fine_dust", "tiny_fine_dust"] as string[];
var powder_parts = ["powder", "small_powder", "tiny_powder"] as string[];
var ore_parts = ["ore_sample", "rock", "ore_rock", "cluster", "clump", "shard", "crushed_ore", "small_crushed_ore", "purified_ore", "small_purified_ore", "centrifuged_ore", "small_centrifuged_ore", "pure_dust", "raw_ore", "chunk", "scrap", "large_scrap"] as string[];
var gem_parts = ["gem", "chipped_gem", "flawed_gem", "crystal", "flawless_gem", "exquisite_gem", "superior_gem", "piece", "lens"] as string[];
var smelt_parts = ["molten", "ingot", "morsel", "nugget", "casing", "plate", "curved_plate", "tough_plate", "dense_plate", "small_rod", "rod", "long_rod", "small_spring", "large_spring", "beam", "bolt", "screw", "round", "foil", "ring", "small_gear", "gear", "small_plate", "spring", "chain", "rail", "large_plate", "small_bolt", "small_casing", "small_screwed_plate"] as string[];
var conductive_parts = ["wire", "fine_wire", "dense_wire", "coil"] as string[];
var blast_parts = ["hot_ingot"] as string[];
var machine_parts = ["turbine_blade", "drill_head", "saw_blade", "rotor", "gearbox"] as string[];
var string_parts = ["fiber", "fibers", "dense_fibers"] as string[];
var semi_conductive_parts = ["boule", "infused_boule", "wafer", "infused_wafer"] as string[];
var wood_parts = ["wood_plate", "stick", "long_stick"] as string[];
var stone_parts = ["stone_plate", "pebble"] as string[];

# -materials
var oak = MaterialSystem.getMaterialBuilder().setName("Oak").setColor(Color.fromHex("966f35")).build();
var spruce = MaterialSystem.getMaterialBuilder().setName("Spruce").setColor(Color.fromHex("734712")).build();
var birch = MaterialSystem.getMaterialBuilder().setName("Birch").setColor(Color.fromHex("e0d1a4")).build();
var jungle = MaterialSystem.getMaterialBuilder().setName("Jungle").setColor(Color.fromHex("d19e71")).build();
var acacia = MaterialSystem.getMaterialBuilder().setName("Acacia").setColor(Color.fromHex("d1732c")).build();
var dark_oak = MaterialSystem.getMaterialBuilder().setName("Dark Oak").setColor(Color.fromHex("472104")).build();
var andesite = MaterialSystem.getMaterialBuilder().setName("Andesite").setColor(Color.fromHex("d5dbdb")).build();
var basalt = MaterialSystem.getMaterialBuilder().setName("Basalt").setColor(Color.fromHex("414d4c")).build();
var blue_schist = MaterialSystem.getMaterialBuilder().setName("Blue Schist").setColor(Color.fromHex("36918e")).build();
var green_schist = MaterialSystem.getMaterialBuilder().setName("Green Schist").setColor(Color.fromHex("3d805f")).build();
var chalk = MaterialSystem.getMaterialBuilder().setName("Chalk").setColor(Color.fromHex("ded0ca")).build();
var dacite = MaterialSystem.getMaterialBuilder().setName("Dacite").setColor(Color.fromHex("d5dbdb")).build();
var dolomite = MaterialSystem.getMaterialBuilder().setName("Dolomite").setColor(Color.fromHex("65705e")).build();
var eclogite = MaterialSystem.getMaterialBuilder().setName("Ecelogite").setColor(Color.fromHex("918273")).build();
var gabbro = MaterialSystem.getMaterialBuilder().setName("Gabbro").setColor(Color.fromHex("7e7985")).build();
var gneiss = MaterialSystem.getMaterialBuilder().setName("Gneiss").setColor(Color.fromHex("595c63")).build();
var greywacke = MaterialSystem.getMaterialBuilder().setName("Greywacke").setColor(Color.fromHex("bcc2be")).build();
var komatiite = MaterialSystem.getMaterialBuilder().setName("komatiite").setColor(Color.fromHex("dbb856")).build();
var limestone = MaterialSystem.getMaterialBuilder().setName("Limestone").setColor(Color.fromHex("bccca3")).build();
var marble = MaterialSystem.getMaterialBuilder().setName("Marble").setColor(Color.fromHex("e3e8e7")).build();
var migmatite = MaterialSystem.getMaterialBuilder().setName("Migmatite").setColor(Color.fromHex("6e7985")).build();
var quartzite = MaterialSystem.getMaterialBuilder().setName("Quartzite").setColor(Color.fromHex("91857d")).build();
var rhyolite = MaterialSystem.getMaterialBuilder().setName("Rhyolite").setColor(Color.fromHex("7b877b")).build();
var shale = MaterialSystem.getMaterialBuilder().setName("Shale").setColor(Color.fromHex("abadb8")).build();
var siltstone = MaterialSystem.getMaterialBuilder().setName("Siltstone").setColor(Color.fromHex("ab8572")).build();
var soapstone = MaterialSystem.getMaterialBuilder().setName("Soapstone").setColor(Color.fromHex("c0c9d1")).build();
var slate = MaterialSystem.getMaterialBuilder().setName("Slate").setColor(Color.fromHex("454852")).build();
var red_granite = MaterialSystem.getMaterialBuilder().setName("Red Granite").setColor(Color.fromHex("bd8f86")).build();
var black_granite = MaterialSystem.getMaterialBuilder().setName("Black Granite").setColor(Color.fromHex("262321")).build();
var wool = MaterialSystem.getMaterialBuilder().setName("Wool").setColor(15922423).build();
var bauxite = MaterialSystem.getMaterialBuilder().setName("Bauxite").setColor(16751481).build();
var galena = MaterialSystem.getMaterialBuilder().setName("Galena").setColor(11499702).build();
var lithium = MaterialSystem.getMaterialBuilder().setName("Lithium").setColor(11844740).build();
var beryllium = MaterialSystem.getMaterialBuilder().setName("Beryllium").setColor(994575).build();
var boron = MaterialSystem.getMaterialBuilder().setName("Boron").setColor(3554609).build();
var carbon = MaterialSystem.getMaterialBuilder().setName("Carbon").setColor(4210752).build();
var sodium = MaterialSystem.getMaterialBuilder().setName("Sodium").setColor(3217).build();
var magnesium = MaterialSystem.getMaterialBuilder().setName("Magnesium").setColor(14262243).build();
var aluminium = MaterialSystem.getMaterialBuilder().setName("Aluminium").setColor(7332333).build();
var phosphorus = MaterialSystem.getMaterialBuilder().setName("Phosphorus").setColor(8014087).build();
var sulfur = MaterialSystem.getMaterialBuilder().setName("Sulfur").setColor(10717970).build();
var potassium = MaterialSystem.getMaterialBuilder().setName("Potassium").setColor(13420197).build();
var calcium = MaterialSystem.getMaterialBuilder().setName("Calcium").setColor(16773811).build();
var scandium = MaterialSystem.getMaterialBuilder().setName("Scandium").setColor(6855831).build();
var titanium = MaterialSystem.getMaterialBuilder().setName("Titanium").setColor(14915803).build();
var vanadium = MaterialSystem.getMaterialBuilder().setName("Vanadium").setColor(2435123).build();
var chrome = MaterialSystem.getMaterialBuilder().setName("Chrome").setColor(16638207).build();
var manganese = MaterialSystem.getMaterialBuilder().setName("Manganese").setColor(14730719).build();
var iron = MaterialSystem.getMaterialBuilder().setName("Iron").setColor(14276569).build();
var cobalt = MaterialSystem.getMaterialBuilder().setName("Cobalt").setColor(3232488).build();
var nickel = MaterialSystem.getMaterialBuilder().setName("Nickel").setColor(15128234).build();
var copper = MaterialSystem.getMaterialBuilder().setName("Copper").setColor(16103251).build();
var zinc = MaterialSystem.getMaterialBuilder().setName("Zinc").setColor(14345704).build();
var gallium = MaterialSystem.getMaterialBuilder().setName("Gallium").setColor(7718826).build();
var germanium = MaterialSystem.getMaterialBuilder().setName("Germanium").setColor(15398137).build();
var arsenic = MaterialSystem.getMaterialBuilder().setName("Arsenic").setColor(13620419).build();
var selenium = MaterialSystem.getMaterialBuilder().setName("Selenium").setColor(6491662).build();
var rubidium = MaterialSystem.getMaterialBuilder().setName("Rubidium").setColor(8737105).build();
var strontium = MaterialSystem.getMaterialBuilder().setName("Strontium").setColor(11577476).build();
var yttrium = MaterialSystem.getMaterialBuilder().setName("Yttrium").setColor(11651499).build();
var zirconium = MaterialSystem.getMaterialBuilder().setName("Zirconium").setColor(11909171).build();
var niobium = MaterialSystem.getMaterialBuilder().setName("Niobium").setColor(6038635).build();
var molybdenum = MaterialSystem.getMaterialBuilder().setName("Molybdenum").setColor(12229588).build();
var technetium = MaterialSystem.getMaterialBuilder().setName("Technetium").setColor(11661274).build();
var ruthenium = MaterialSystem.getMaterialBuilder().setName("Ruthenium").setColor(15393767).build();
var rhodium = MaterialSystem.getMaterialBuilder().setName("Rhodium").setColor(15723243).build();
var palladium = MaterialSystem.getMaterialBuilder().setName("Palladium").setColor(7218943).build();
var silver = MaterialSystem.getMaterialBuilder().setName("Silver").setColor(14808562).build();
var cadmium = MaterialSystem.getMaterialBuilder().setName("Cadmium").setColor(4222617).build();
var indium = MaterialSystem.getMaterialBuilder().setName("Indium").setColor(9109685).build();
var tin = MaterialSystem.getMaterialBuilder().setName("Tin").setColor(2978815).build();
var antimony = MaterialSystem.getMaterialBuilder().setName("Antimony").setColor(15457451).build();
var tellurium = MaterialSystem.getMaterialBuilder().setName("Tellurium").setColor(5411230).build();
var iodine = MaterialSystem.getMaterialBuilder().setName("Iodine").setColor(6239080).build();
var caesium = MaterialSystem.getMaterialBuilder().setName("Caesium").setColor(10789037).build();
var barium = MaterialSystem.getMaterialBuilder().setName("Barium").setColor(11029780).build();
var lanthanum = MaterialSystem.getMaterialBuilder().setName("Lanthanum").setColor(9872043).build();
var cerium = MaterialSystem.getMaterialBuilder().setName("Cerium").setColor(5334645).build();
var praseodymium = MaterialSystem.getMaterialBuilder().setName("Praseodymium").setColor(1457497).build();
var neodymium = MaterialSystem.getMaterialBuilder().setName("Neodymium").setColor(7500423).build();
var promethium = MaterialSystem.getMaterialBuilder().setName("Promethium").setColor(11235985).build();
var samarium = MaterialSystem.getMaterialBuilder().setName("Samarium").setColor(4745561).build();
var europium = MaterialSystem.getMaterialBuilder().setName("Europium").setColor(10255989).build();
var gadolinium = MaterialSystem.getMaterialBuilder().setName("Gadolinium").setColor(12236940).build();
var terbium = MaterialSystem.getMaterialBuilder().setName("Terbium").setColor(7899738).build();
var dysprosium = MaterialSystem.getMaterialBuilder().setName("Dysprosium").setColor(7221332).build();
var holmium = MaterialSystem.getMaterialBuilder().setName("Holmium").setColor(8879725).build();
var erbium = MaterialSystem.getMaterialBuilder().setName("Erbium").setColor(7178111).build();
var thulium = MaterialSystem.getMaterialBuilder().setName("Thulium").setColor(468802).build();
var ytterbium = MaterialSystem.getMaterialBuilder().setName("Ytterbium").setColor(4144970).build();
var lutetium = MaterialSystem.getMaterialBuilder().setName("Lutetium").setColor(8099996).build();
var hafnium = MaterialSystem.getMaterialBuilder().setName("Hafnium").setColor(11516878).build();
var tantalum = MaterialSystem.getMaterialBuilder().setName("Tantalum").setColor(12373199).build();
var tungsten = MaterialSystem.getMaterialBuilder().setName("Tungsten").setColor(1052708).build();
var rhenium = MaterialSystem.getMaterialBuilder().setName("Rhenium").setColor(14668527).build();
var osmium = MaterialSystem.getMaterialBuilder().setName("Osmium").setColor(255).build();
var iridium = MaterialSystem.getMaterialBuilder().setName("Iridium").setColor(15597565).build();
var platinum = MaterialSystem.getMaterialBuilder().setName("Platinum").setColor(13555675).build();
var gold = MaterialSystem.getMaterialBuilder().setName("Gold").setColor(16767324).build();
var mercury = MaterialSystem.getMaterialBuilder().setName("Mercury").setColor(16735324).build();
var thallium = MaterialSystem.getMaterialBuilder().setName("Thallium").setColor(13031410).build();
var lead = MaterialSystem.getMaterialBuilder().setName("Lead").setColor(9925035).build();
var bismuth = MaterialSystem.getMaterialBuilder().setName("Bismuth").setColor(5543022).build();
var polonium = MaterialSystem.getMaterialBuilder().setName("Polonium").setColor(6701599).build();
var astatine = MaterialSystem.getMaterialBuilder().setName("Astatine").setColor(2763568).build();
var francium = MaterialSystem.getMaterialBuilder().setName("Francium").setColor(4409926).build();
var radium = MaterialSystem.getMaterialBuilder().setName("Radium").setColor(13092533).build();
var actinium = MaterialSystem.getMaterialBuilder().setName("Actinium").setColor(4284353).build();
var thorium = MaterialSystem.getMaterialBuilder().setName("Thorium").setColor(2759734).build();
var protactinium = MaterialSystem.getMaterialBuilder().setName("Protactinium").setColor(14344178).build();
var uranium = MaterialSystem.getMaterialBuilder().setName("Uranium").setColor(65356).build();
var neptunium = MaterialSystem.getMaterialBuilder().setName("Neptunium").setColor(4935139).build();
var plutonium = MaterialSystem.getMaterialBuilder().setName("Plutonium").setColor(11250900).build();
var americium = MaterialSystem.getMaterialBuilder().setName("Americium").setColor(16753538).build();
var curium = MaterialSystem.getMaterialBuilder().setName("Curium").setColor(3883110).build();
var berkelium = MaterialSystem.getMaterialBuilder().setName("Berkelium").setColor(8544025).build();
var californium = MaterialSystem.getMaterialBuilder().setName("Californium").setColor(12862224).build();
var einsteinium = MaterialSystem.getMaterialBuilder().setName("Einsteinium").setColor(927620).build();
var fermium = MaterialSystem.getMaterialBuilder().setName("Fermium").setColor(11251577).build();
var mendelevium = MaterialSystem.getMaterialBuilder().setName("Mendelevium").setColor(7974825).build();
var nobelium = MaterialSystem.getMaterialBuilder().setName("Nobelium").setColor(10910127).build();
var lawrencium = MaterialSystem.getMaterialBuilder().setName("Lawrencium").setColor(12694339).build();
var rutherfordium = MaterialSystem.getMaterialBuilder().setName("Rutherfordium").setColor(13942695).build();
var dubnium = MaterialSystem.getMaterialBuilder().setName("Dubnium").setColor(11913671).build();
var seaborgium = MaterialSystem.getMaterialBuilder().setName("Seaborgium").setColor(10339271).build();
var bohrium = MaterialSystem.getMaterialBuilder().setName("Bohrium").setColor(6045503).build();
var hassium = MaterialSystem.getMaterialBuilder().setName("Hassium").setColor(9402705).build();
var meitnerium = MaterialSystem.getMaterialBuilder().setName("Meitnerium").setColor(11573163).build();
var darmstadtium = MaterialSystem.getMaterialBuilder().setName("Darmstadtium").setColor(13559473).build();
var roentgenium = MaterialSystem.getMaterialBuilder().setName("Roentgenium").setColor(6253411).build();
var copernicium = MaterialSystem.getMaterialBuilder().setName("Copernicium").setColor(8162447).build();
var nihonium = MaterialSystem.getMaterialBuilder().setName("Nihonium").setColor(11057842).build();
var flerovium = MaterialSystem.getMaterialBuilder().setName("Flerovium").setColor(12239820).build();
var moscovium = MaterialSystem.getMaterialBuilder().setName("Moscovium").setColor(12747380).build();
var livermorium = MaterialSystem.getMaterialBuilder().setName("Livermorium").setColor(11380859).build();
var tennessine = MaterialSystem.getMaterialBuilder().setName("Tennessine").setColor(10649312).build();
var oganesson = MaterialSystem.getMaterialBuilder().setName("Oganesson").setColor(9737364).build();
var kanthal = MaterialSystem.getMaterialBuilder().setName("Kanthal").setColor(11251019).build();
var nichrome = MaterialSystem.getMaterialBuilder().setName("Nichrome").setColor(12484095).build();
var tinalloy = MaterialSystem.getMaterialBuilder().setName("Tin Alloy").setColor(11193548).build();
var magnalium = MaterialSystem.getMaterialBuilder().setName("Magnalium").setColor(4809345).build();
var rosegold = MaterialSystem.getMaterialBuilder().setName("Rose Gold").setColor(15624262).build();
var sterlingsilver = MaterialSystem.getMaterialBuilder().setName("Sterling Silver").setColor(13558754).build();
var niobiumtitanium = MaterialSystem.getMaterialBuilder().setName("Niobium Titanium").setColor(13857394).build();
var bluesteel = MaterialSystem.getMaterialBuilder().setName("Blue Steel").setColor(221871).build();
var redsteel = MaterialSystem.getMaterialBuilder().setName("Red Steel").setColor(11867927).build();
var stainlesssteel = MaterialSystem.getMaterialBuilder().setName("Stainless Steel").setColor(10197429).build();
var cobaltbrass = MaterialSystem.getMaterialBuilder().setName("Cobalt Brass").setColor(2379151).build();
var bismuthbronze = MaterialSystem.getMaterialBuilder().setName("Bismuth Bronze").setColor(3563573).build();
var blackbronze = MaterialSystem.getMaterialBuilder().setName("Black Bronze").setColor(7166495).build();
var blacksteel = MaterialSystem.getMaterialBuilder().setName("Black Steel").setColor(3094856).build();
var pewter = MaterialSystem.getMaterialBuilder().setName("Pewter").setColor(12308907).build();
var galvanized_steel = MaterialSystem.getMaterialBuilder().setName("Galvanized Steel").setColor(7831390).build();
var tungstensteel = MaterialSystem.getMaterialBuilder().setName("Tungstensteel").setColor(1778737).build();
var iridium_alloy = MaterialSystem.getMaterialBuilder().setName("Iridium Alloy").setColor(15396846).build();
var advanced_alloy = MaterialSystem.getMaterialBuilder().setName("Advanced Alloy").setColor(15222313).build();
var bronze = MaterialSystem.getMaterialBuilder().setName("Bronze").setColor(16746522).build();
var electrum = MaterialSystem.getMaterialBuilder().setName("Electrum").setColor(16377344).build();
var constantan = MaterialSystem.getMaterialBuilder().setName("Constantan").setColor(16604183).build();
var steel = MaterialSystem.getMaterialBuilder().setName("Steel").setColor(8821403).build();
var brass = MaterialSystem.getMaterialBuilder().setName("Brass").setColor(15906304).build();
var invar = MaterialSystem.getMaterialBuilder().setName("Invar").setColor(11578986).build();
var hssg = MaterialSystem.getMaterialBuilder().setName("HSS G").setColor(9606196).build();
var hsse = MaterialSystem.getMaterialBuilder().setName("HSS E").setColor(3365930).build();
var hsss = MaterialSystem.getMaterialBuilder().setName("HSS S").setColor(6498366).build();
var dilithium = MaterialSystem.getMaterialBuilder().setName("Dilithium").setColor(15000250).build();
var titanium_aluminide = MaterialSystem.getMaterialBuilder().setName("Titanium Aluminide").setColor(212295).build();
var titanium_iridium = MaterialSystem.getMaterialBuilder().setName("Titanium Iridium").setColor(15316149).build();
var redstone_alloy = MaterialSystem.getMaterialBuilder().setName("Redstone Alloy").setColor(15346197).build();
var electrical_steel = MaterialSystem.getMaterialBuilder().setName("Electrical Steel").setColor(11119794).build();
var conductive_iron = MaterialSystem.getMaterialBuilder().setName("Conductive Iron").setColor(12033434).build();
var dark_steel = MaterialSystem.getMaterialBuilder().setName("Dark Steel").setColor(3027759).build();
var construction_alloy = MaterialSystem.getMaterialBuilder().setName("Construction Alloy").setColor(11907469).build();
var alumite = MaterialSystem.getMaterialBuilder().setName("Alumite").setColor(16763376).build();
var osmiridium = MaterialSystem.getMaterialBuilder().setName("Osmiridium").setColor(7969224).build();
var redalloy = MaterialSystem.getMaterialBuilder().setName("Red Alloy").setColor(16711680).build();
var electrum_flux = MaterialSystem.getMaterialBuilder().setName("Gelid Enderium").setColor(16035876).build();
var signalum = MaterialSystem.getMaterialBuilder().setName("Signalum").setColor(16660993).build();
var lumium = MaterialSystem.getMaterialBuilder().setName("Lumium").setColor(16777145).build();
var enderium = MaterialSystem.getMaterialBuilder().setName("Enderium").setColor(34873).build();
var aluminum_brass = MaterialSystem.getMaterialBuilder().setName("Aluminum Brass").setColor(15913032).build();
var knightslime = MaterialSystem.getMaterialBuilder().setName("Knightslime").setColor(13058520).build();
var pig_iron = MaterialSystem.getMaterialBuilder().setName("Pig Iron").setColor(14853790).build();
var cupronickel = MaterialSystem.getMaterialBuilder().setName("Cupronickel").setColor(14192917).build();
var aluminum_bronze = MaterialSystem.getMaterialBuilder().setName("Aluminum Bronze").setColor(15901512).build();
var nickel_aluminum_bronze = MaterialSystem.getMaterialBuilder().setName("NickelAluminum Bronze").setColor(15389836).build();
var yttrium_barium_cuprate = MaterialSystem.getMaterialBuilder().setName("Yttrium Barium Cuprate").setColor(3869704).build();
var purple_steel = MaterialSystem.getMaterialBuilder().setName("Purple Steel").setColor(7405677).build();
var voidensteel = MaterialSystem.getMaterialBuilder().setName("Voidensteel").setColor(5443893).build();
var white_gold = MaterialSystem.getMaterialBuilder().setName("White Gold").setColor(16776388).build();
var nichromium = MaterialSystem.getMaterialBuilder().setName("Nichromium").setColor(9720402).build();
var chromodium = MaterialSystem.getMaterialBuilder().setName("Chromodium").setColor(8061989).build();
var fluxalitium = MaterialSystem.getMaterialBuilder().setName("Fluxalitium").setColor(16769175).build();
var spectraclium = MaterialSystem.getMaterialBuilder().setName("Spectraclium").setColor(15269886).build();
var obsidian = MaterialSystem.getMaterialBuilder().setName("Obsidian").setColor(4325442).build();
var nether_star = MaterialSystem.getMaterialBuilder().setName("Nether Star").setColor(Color.fromHex("fafeff")).build();
var green_sapphire = MaterialSystem.getMaterialBuilder().setName("Green Sapphire").setColor(Color.fromHex("47b560")).build();
var diamond = MaterialSystem.getMaterialBuilder().setName("Diamond").setColor(Color.fromHex("c9ffff")).build();
var emerald = MaterialSystem.getMaterialBuilder().setName("Emerald").setColor(Color.fromHex("5ebf3b")).build();
var cinnabar = MaterialSystem.getMaterialBuilder().setName("Cinnabar").setColor(Color.fromHex("751d23")).build();
var coal = MaterialSystem.getMaterialBuilder().setName("Coal").setColor(Color.fromHex("26241f")).build();
var lignite = MaterialSystem.getMaterialBuilder().setName("Lignite").setColor(Color.fromHex("66583e")).build();
var apatite = MaterialSystem.getMaterialBuilder().setName("Apatite").setColor(Color.fromHex("4887b8")).build();
var monazite = MaterialSystem.getMaterialBuilder().setName("Monazite").setColor(Color.fromHex("557864")).build();
var nether_quartz = MaterialSystem.getMaterialBuilder().setName("Nether Quartz").setColor(Color.fromHex("fffcfa")).build();
var sunny_quartz = MaterialSystem.getMaterialBuilder().setName("Sunny Quartz").setColor(Color.fromHex("fffce8")).build();
var rose_quartz = MaterialSystem.getMaterialBuilder().setName("Rose Quartz").setColor(Color.fromHex("ffe8e8")).build();
var elven_quartz = MaterialSystem.getMaterialBuilder().setName("Elven Quartz").setColor(Color.fromHex("e3ffe7")).build();
var mana_quartz = MaterialSystem.getMaterialBuilder().setName("Mana Quartz").setColor(Color.fromHex("e3f4ff")).build();
var lavender_quartz = MaterialSystem.getMaterialBuilder().setName("Lavender Quartz").setColor(Color.fromHex("e5dff0")).build();
var blaze_quartz = MaterialSystem.getMaterialBuilder().setName("Blaze Quartz").setColor(Color.fromHex("fff1de")).build();
var certus_quartz = MaterialSystem.getMaterialBuilder().setName("Certus Quartz").setColor(Color.fromHex("f0f3ff")).build();
var black_quartz = MaterialSystem.getMaterialBuilder().setName("Black Quartz").setColor(2368565).build();
var lava_crystal = MaterialSystem.getMaterialBuilder().setName("Lava Crystal").setColor(13006108).build();
var electrical = MaterialSystem.getMaterialBuilder().setName("Electrical").setColor(11187636).build();
var adamantine = MaterialSystem.getMaterialBuilder().setName("Adamantine").setColor(6175792).build();
var cold_iron = MaterialSystem.getMaterialBuilder().setName("Cold Iron").setColor(11982831).build();
var star_steel = MaterialSystem.getMaterialBuilder().setName("Star Steel").setColor(460057).build();
var aquarium = MaterialSystem.getMaterialBuilder().setName("Aquarium").setColor(2377589).build();
var ruby = MaterialSystem.getMaterialBuilder().setName("Ruby").setColor(11534336).build();
var amber = MaterialSystem.getMaterialBuilder().setName("Amber").setColor(16690275).build();
var topaz = MaterialSystem.getMaterialBuilder().setName("Topaz").setColor(15365376).build();
var peridot = MaterialSystem.getMaterialBuilder().setName("Peridot").setColor(7463168).build();
var malachite = MaterialSystem.getMaterialBuilder().setName("Malachite").setColor(61608).build();
var sapphire = MaterialSystem.getMaterialBuilder().setName("Sapphire").setColor(4522197).build();
var amethyst = MaterialSystem.getMaterialBuilder().setName("Amethyst").setColor(14320383).build();
var tanzanite = MaterialSystem.getMaterialBuilder().setName("Tanzanite").setColor(4788089).build();
var moonstone = MaterialSystem.getMaterialBuilder().setName("Moonstone").setColor(4343142).build();
var red_garnet = MaterialSystem.getMaterialBuilder().setName("Red Garnet").setColor(14367804).build();
var yellow_garnet = MaterialSystem.getMaterialBuilder().setName("Yellow Garnet").setColor(14081590).build();
var aquamarine = MaterialSystem.getMaterialBuilder().setName("Aquamarine").setColor(2268386).build();

# -ores
var lumiumOre = lumium.registerPart("ore");
lumiumOre.addDataValue("variants","minecraft:stone,minecraft:netherrack,minecraft:end_stone");
lumiumOre.addDataValue("hardness","5,5,5");
lumiumOre.addDataValue("resistance","6,6,9");
lumiumOre.addDataValue("harvestTool","pickaxe,pickaxe,pickaxe");
lumiumOre.addDataValue("harvestLevel","2,2,2");

var lumiumOre = lumium.registerPart("ore");
lumiumPoorOre.addDataValue("variants","minecraft:stone,minecraft:netherrack,minecraft:end_stone");
lumiumPoorOre.addDataValue("hardness","5,5,5");
lumiumPoorOre.addDataValue("resistance","6,6,9");
lumiumPoorOre.addDataValue("harvestTool","pickaxe,pickaxe,pickaxe");
lumiumPoorOre.addDataValue("harvestLevel","2,2,2");

var lumiumOre = lumium.registerPart("ore");
lumiumDenseOre.addDataValue("variants","minecraft:stone,minecraft:netherrack,minecraft:end_stone,minecraft:bedrock");
lumiumDenseOre.addDataValue("hardness","5,5,5,70");
lumiumDenseOre.addDataValue("resistance","6,6,9,1200");
lumiumDenseOre.addDataValue("harvestTool","pickaxe,pickaxe,pickaxe,pickaxe");
lumiumDenseOre.addDataValue("harvestLevel","2,2,2,3");



